const travelMates = [
  {
    name: "Sarah Chen",
    age: 28,
    location: "San Francisco, CA",
    destination: "Tokyo",
    travelStyle: "Adventure",
    duration: "1 Month",
    groupSize: "small",
    experience: "first-timer",
    bio: "Excited to explore Tokyo and find like-minded travel buddies.",
  },
  {
    name: "David Park",
    age: 35,
    location: "Seoul, South Korea",
    destination: "Bali",
    travelStyle: "Relaxation",
    duration: "1 Week",
    groupSize: "medium",
    experience: "experienced",
    bio: "Seasoned traveler looking to unwind in Bali.",
  },
  {
    name: "Alex Thompson",
    age: 26,
    location: "New York, USA",
    destination: "Iceland",
    travelStyle: "Adventure",
    duration: "Weekend",
    groupSize: "solo",
    experience: "first-timer",
    bio: "Ready for my first solo trip into the wild beauty of Iceland.",
  },
  {
    name: "Priya Sharma",
    age: 32,
    location: "Mumbai, India",
    destination: "Tokyo",
    travelStyle: "Cultural",
    duration: "1 Week",
    groupSize: "medium",
    experience: "experienced",
    bio: "History buff looking to explore Tokyo’s ancient and modern culture.",
  },
  {
    name: "Liam Nguyen",
    age: 30,
    location: "Hanoi, Vietnam",
    destination: "Nepal",
    travelStyle: "Adventure",
    duration: "1 Month",
    groupSize: "small",
    experience: "experienced",
    bio: "Mountaineering enthusiast heading for the Himalayas.",
  },
  {
    name: "Emily Clark",
    age: 27,
    location: "London, UK",
    destination: "Patagonia",
    travelStyle: "Adventure",
    duration: "1 Month",
    groupSize: "medium",
    experience: "first-timer",
    bio: "Seeking thrill and peace in Patagonia’s vastness.",
  },
];

export default travelMates;